import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'

import {
    GoogleOutlined, FacebookOutlined, LinkedinOutlined,
    TwitterOutlined,
    LoadingOutlined
} from '@ant-design/icons'
import AddressActions from '../actions/address'

export default function Countries() {
    const dispatch = useDispatch()
    const [selectedTab, setSelectedTab] = useState('All')

    const {
        fetchingCountries, fetchCountriesSuccessful, countries
    } = useSelector(state => state.address)

    useEffect(() => {
        dispatch(AddressActions.stateReset({

            fetchingCountries: false,
            fetchCountriesSuccessful: false,
            countries: []

        }))
    }, [])

    useEffect(() => {
        dispatch(AddressActions.getCountriesRequest())
    }, [])

    useEffect(() => {
        if (!fetchingCountries && fetchCountriesSuccessful) {
            dispatch(AddressActions.stateReset({ fetchCountriesSuccessful: false }))
        }
    }, [fetchCountriesSuccessful])

    return (
        <Wrapper className={styles.container}>
            <Head>
                <title>Interview App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='fullContainer'>
                <div className='titleWrap'>
                    <div className='title'>Contries</div>
                    <div className='tabsection'>
                        {
                            ['All', 'Asia', 'Europe'].map((tab, index) =>
                                <div className={selectedTab === tab ? 'tabItem active' : 'tabItem'} key={index} onClick={() => setSelectedTab(tab)}>{tab}</div>
                            )
                        }
                    </div>

                </div>
                <div className='contentWrap'>
                    {

                        fetchingCountries
                            ? <LoadingOutlined />
                            : selectedTab === 'All'
                                ? countries.map((country, index) =>
                                    <div className='tabitem' key={index} >
                                        <div className="cardImg" style={{ backgroundImage: `url(${country.flag || null})`, backgroundRepeat: 'no-repeat', backgroundPosition: 'center', backgroundSize: 'cover' }} />
                                        <div className='contentSection'>
                                            <div style={{ fontWeight: 500 }}>{country.name}</div>
                                            <div>{country.region}</div>
                                        </div>
                                    </div>
                                )
                                :
                                countries.filter((filter) => filter.region === selectedTab).map((country, index) =>
                                    <div className='tabitem' key={index} >
                                        <div className="cardImg" style={{ backgroundImage: `url(${country.flag || null})`, backgroundRepeat: 'no-repeat', backgroundPosition: 'center', backgroundSize: 'cover' }} />
                                        <div className='contentSection'>
                                            <div style={{ fontWeight: 500 }}>{country.name}</div>
                                            <div>{country.region}</div>
                                        </div>
                                    </div>
                                )
                    }
                </div>
                {

                    fetchingCountries
                        ? null
                        : (
                            <div className='pagefooter'>
                                <div className='socialmediaSection'>
                                    <div className='socialIconRound'><GoogleOutlined /></div>
                                    <div className='socialIconRound'><FacebookOutlined /></div>
                                    <div className='socialIconRound'><LinkedinOutlined /></div>
                                    <div className='socialIconRound'><TwitterOutlined /></div>
                                </div>
                                <div>example@gmail.com </div>
                                <div style={{ marginBottom: '40px' }}>Copyright 2022 Name. All Right Reserved</div>
                            </div>

                        )
                }
            </div>
        </Wrapper>
    )
}
const Wrapper = styled.section`
	background-color: #fff;
	width: 100%;
	max-width: 100vw;
	height: 100%;
	min-height: 100vh;
	display: flex;
	align-items: center;
	justify-content: center;
	/* position: absolute; */

	.fullContainer {
		display: flex;
		width: 100vw;
		height: 100vh;
		flex-direction: column;
		justify-content: flex-start;
		align-items: flex-start;
        padding: 40px;
        .titleWrap{
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            .title{
                font-size: 20px;
                font-weight: 500;
            }
            .tabsection{
                width: 200px;
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: center;
                .tabItem{
                    width: 80px;
                    display: flex;
                    cursor: pointer;
                    flex-direction: row;
                    justify-content: center;
                    align-items: center;

                }
                .active{
                    border-bottom: 1px solid #1890ff;
                }
            }

        }
        .contentWrap{
            display: flex;
            width: 100%;
            flex-wrap: wrap;
            flex-direction: row;
            justify-content: space-between;
            align-items: flex-start;
            padding-top: 20px;
            .tabitem{
                width: 45%;
                display: flex;
                flex-direction: row;
                justify-content: flex-start;
                align-items: center;
                margin-bottom: 20px;
                padding: 20px;
                background-color: #f0f0f0;
                border: 1px solid #000;
                .cardImg{
                    width: 64px;
                    height: 64px;
                }
                .contentSection{
                    display: flex;
                    flex-direction: column;
                    justify-content: flex-start;
                    align-items: flex-start;
                    padding-left: 20px;
                }
                @media screen and (max-width: 700px) {
                    width: 100%;
                }
            }
        }
        .pagefooter{
            display: flex;
            width: 100%;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            padding-top: 20px;
            .socialmediaSection{
                width: 300px;
                display: flex;
                flex-direction: row;
                align-items: center;
                justify-content: space-between;
                padding: 20px 40px;
                .socialIconRound{
                    display: flex;
                    flex-direction: row;
                    align-items: center;
                    justify-content: center;
                    width: 40px;
                    height: 40px;
                    border-radius: 100%;
                    border: 1px solid #000;
                }
            }
        }

    }

`

