import Head from 'next/head'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import { Button, Input, message } from 'antd'
import Checkbox from 'antd/lib/checkbox/Checkbox'
import {
  GoogleOutlined, FacebookOutlined, LinkedinOutlined,
  TwitterOutlined
} from '@ant-design/icons'
import Router from 'next/router'

export default function Home() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [requredLogenIn, setRequredLogenIn] = useState(false)

  const handelSubmit = () => {
    if (username === '' && password === '') {
      message.error('Please provide user name and password')
    } else {
      Router.push('/countries')
    }
  }
  return (
    <Wrapper className={styles.container}>
      <Head>
        <title>Interview App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='fullContainer'>
        <div className='formmSection'>
          <h2>Sign In</h2>
          <div style={{ fontWeight: 500, padding: '20px 0px' }}>New user ? <a className='link'>Create an account</a></div>
          <Input
            placeholder='Username or Email'
            className="loginInput"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />

          <Input
            placeholder='Password'
            className="loginInput"
            value={password}
            type="password"
            onChange={(e) => setPassword(e.target.value)}
          />
          <Checkbox style={{ fontWeight: 500 }} defaultChecked={false} value={requredLogenIn} onChange={(e) => setRequredLogenIn(e.target.checked)}>Keep me signed in</Checkbox>
          <Button type='primary' className='loginButton' onClick={() => handelSubmit()}>Sign In</Button>
          <div className='loginSocialTitleWrap'>
            <div className='backgroundLine'></div>
            <div className='loginSocialTitle'>
              Or Sign In With
            </div>
          </div>
          <div className='socialmediaSection'>
            <div className='socialIconRound'><GoogleOutlined /></div>
            <div className='socialIconRound'><FacebookOutlined /></div>
            <div className='socialIconRound'><LinkedinOutlined /></div>
            <div className='socialIconRound'><TwitterOutlined /></div>
          </div>
        </div>
        <div className='imageSection'></div>
      </div>
    </Wrapper>
  )
}
const Wrapper = styled.section`
	background-color: #fff;
	width: 100%;
	max-width: 100vw;
	height: 100%;
	min-height: 100vh;
	display: flex;
	align-items: center;
	justify-content: center;
	position: absolute;

	.fullContainer {
		display: flex;
		flex: 1;
		position: absolute;
		left: 0;
		width: 100vw;
		height: 100vh;
		flex-direction: row;
		justify-content: center;
		align-items: center;
		z-index: 100;

    .formmSection{
      width: 50%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      .ant-checkbox{
        margin-right: 10px !important;
      }
      .link{
        color: #1890ff;
        cursor: pointer;
      }
      .loginInput{
        width: 400px;
        padding-left: 10px;
        height: 35px;   
        border-radius: 3px;
        border-width: .5px;
        border-style: solid;
        border-color: #000;
        background-color:#f0f0f0;
        color: #000;
        font-size: small;
  			resize: none;
        margin-bottom: 40px;
      }
      .loginButton{
        width:400px;
        height: 35px;
        background-color: #000;
        color: #fff;
        margin-top: 40px;
      }
      .loginSocialTitleWrap{
        width: 400px;
        position: relative;
        margin-top: 40px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        .loginSocialTitle{
          height: 40px;
          background-color: #fff;
          z-index: 1;
          padding: 0px 10px;

        }
        .backgroundLine{
          position: absolute;
          top: 10px;
          left: 0;
          width: 400px;
          height: 5px;
          background-color: #f0f0f0;
        }
      }
      .socialmediaSection{
        width: 400px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        padding: 20px 40px;
        .socialIconRound{
          display: flex;
          flex-direction: row;
          align-items: center;
          justify-content: center;
          width: 40px;
          height: 40px;
          border-radius: 100%;
          border: 1px solid #000;
        }
      }
    }
   
    .imageSection{
      width: 50%;
      height: 80vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      background: url('login-img.jpg') no-repeat center;
      background-size: contain;
      @media screen and (max-width: 700px) {
        display: none;
      }
    }
	
	}

`

